[template.environment]
  AIRTABLEAPIKEY = "Your Airtable API Key"
  AIRTABLEBASE = "Your Airtable Base"
  AIRTABLEVIEW="Your Airtable View"

[build]
  base = "website/"
  publish= ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"
